// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGBackend.Data;

#nullable disable

namespace Lagom.Data.Migrations
{
    [DbContext(typeof(LagomDbContext))]
    partial class LagomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lagom.Model.AppLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            IsActive = true,
                            Name = "English",
                            NativeName = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "it",
                            IsActive = true,
                            Name = "Italian",
                            NativeName = "Italiano"
                        });
                });

            modelBuilder.Entity("Lagom.Model.AppMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppLanguageId");

                    b.ToTable("AppMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppLanguageId = 1,
                            Code = "login.credentials.required",
                            Message = "Username and password are required",
                            Severity = "error",
                            Type = "login"
                        },
                        new
                        {
                            Id = 2,
                            AppLanguageId = 2,
                            Code = "login.credentials.required",
                            Message = "Username e password sono obbligatori",
                            Severity = "error",
                            Type = "login"
                        },
                        new
                        {
                            Id = 3,
                            AppLanguageId = 1,
                            Code = "login.credentials.invalid",
                            Message = "Invalid username or password",
                            Severity = "error",
                            Type = "login"
                        },
                        new
                        {
                            Id = 4,
                            AppLanguageId = 2,
                            Code = "login.credentials.invalid",
                            Message = "Username o password non validi",
                            Severity = "error",
                            Type = "login"
                        },
                        new
                        {
                            Id = 5,
                            AppLanguageId = 1,
                            Code = "user.creation.error",
                            Message = "Something went wrong while trying to create the user",
                            Severity = "error",
                            Type = "user.creation"
                        },
                        new
                        {
                            Id = 6,
                            AppLanguageId = 2,
                            Code = "user.creation.error",
                            Message = "Qualcosa è andato storto durante la creazione dell'utente.",
                            Severity = "error",
                            Type = "user.creation"
                        });
                });

            modelBuilder.Entity("Lagom.Model.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full control",
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Can run example controller routes",
                            Name = "example"
                        });
                });

            modelBuilder.Entity("Lagom.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessKeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessKeyHash = "21232f297a57a5a743894a0e4a801fc3",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessKeyHash = "21232f297a57a5a743894a0e4a801fc3",
                            FirstName = "Moreno",
                            IsActive = true,
                            LastName = "Bruschi",
                            Username = "moro"
                        });
                });

            modelBuilder.Entity("Lagom.Model.UsersClaims", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UsersClaims");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ClaimId = 1
                        },
                        new
                        {
                            UserId = 2,
                            ClaimId = 2
                        });
                });

            modelBuilder.Entity("Lagom.Model.AppMessage", b =>
                {
                    b.HasOne("Lagom.Model.AppLanguage", "AppLanguage")
                        .WithMany("AppMessages")
                        .HasForeignKey("AppLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppLanguage");
                });

            modelBuilder.Entity("Lagom.Model.UsersClaims", b =>
                {
                    b.HasOne("Lagom.Model.Claim", "Claim")
                        .WithMany("UsersClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lagom.Model.User", "User")
                        .WithMany("UsersClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lagom.Model.AppLanguage", b =>
                {
                    b.Navigation("AppMessages");
                });

            modelBuilder.Entity("Lagom.Model.Claim", b =>
                {
                    b.Navigation("UsersClaims");
                });

            modelBuilder.Entity("Lagom.Model.User", b =>
                {
                    b.Navigation("UsersClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
